### ISSUE TITLE
実践Rustプログラミング入門（第１版第５刷）でコンパイルエラー

### ISSUE THREAD

**Issue by NaokiMatsuzawa** [forcia/rustbook#11]
はじめまして、
実践Rustプログラミング入門（第１版第５刷）
で学習をしておりますが、

本書の通りに書いたにも関わらず、
Chapter4 のderiveマクロを使った記述方式で以下のエラーが発生しました。

[error_log.txt](https://github.com/forcia/rustbook/files/9689544/error_log.txt)

自分でも調べてみましたが原因が分からず行き詰まっております。

大変お忙しい中恐縮ですが、
解決策等お願い致します。

**Comment by dalance** [comment]
こちらで再現できていませんので推測ですがclapのバージョンとソースコードが合っていないのではないかと思います。
https://github.com/forcia/rustbook/tree/master/ch04 はコンパイルできることを確認しましたので、こちらとの差分を見ていただくのがいいかと思います。
あるいはsrc/main.rs, Cargo.toml, Cargo.lock を一式アップロードしていただければ見てみます。

**Comment by NaokiMatsuzawa** [comment]
ご返信ありがとうございます。
src/main.rs, Cargo.toml, Cargo.lock を一式、ZIPにて圧縮したものをアップロードいたします。
よろしくお願い申し上げます。
[4-1_source.zip](https://github.com/forcia/rustbook/files/9703021/4-1_source.zip)

**Comment by dalance** [comment]
Cargo.toml のclapのバージョンを3.2に上げてみてください。

```toml
clap = {version="3.2.0", features=["derive"]}
```

本ではclapを3.0.0指定で追加するようになっていると思いますが、
derive機能を提供するclap_deriveクレートは自動的に3.x系の最新である3.2.18になってしまうようで、不整合を起こしているようです。

**Comment by NaokiMatsuzawa** [comment]
ご返答ありがとうございます。

アドバイス通りに3.2.0に指定したところ、
コンパイルが通るようになりました。

お忙しい中、ありがとうございました。
